### ISSUE TITLE
Import from SFC does not work.

### ISSUE THREAD

**Issue by blowsie** [primefaces/primevue#1025]
I simply took the primevue-quickstart-vite project and changed the usage of button to 
`import Button from 'primevue/button/sfc';`

**Error**
```
[plugin:vite:import-analysis] Failed to resolve import "primevue/button/sfc". Does the file exist?
C:/Projects/github/primevue-quickstart-vite/src/components/HelloWorld.vue:1:21
1  |  import Button from 'primevue/button/sfc';
   |                      ^
2  |  import { reactive } from 'vue'
3  |
    at formatError (C:\Projects\github\primevue-quickstart-vite\node_modules\vite\dist\node\chunks\dep-00e79b84.js:45759:46)
    at TransformContext.error (C:\Projects\github\primevue-quickstart-vite\node_modules\vite\dist\node\chunks\dep-00e79b84.js:45755:19)
    at normalizeUrl (C:\Projects\github\primevue-quickstart-vite\node_modules\vite\dist\node\chunks\dep-00e79b84.js:47244:26)
    at async TransformContext.transform (C:\Projects\github\primevue-quickstart-vite\node_modules\vite\dist\node\chunks\dep-00e79b84.js:47373:57)
    at async Object.transform (C:\Projects\github\primevue-quickstart-vite\node_modules\vite\dist\node\chunks\dep-00e79b84.js:45957:30)
    at async transformRequest (C:\Projects\github\primevue-quickstart-vite\node_modules\vite\dist\node\chunks\dep-00e79b84.js:61528:29)
    at async C:\Projects\github\primevue-quickstart-vite\node_modules\vite\dist\node\chunks\dep-00e79b84.js:61630:32
Click outside or fix the code to dismiss.
You can also disable this overlay with hmr: { overlay: false } in vite.config.js.
```

**Comment by cagataycivici** [comment]
What is your PrimeVue version?

**Comment by blowsie** [comment]
same as 
`primevue-quickstart-vite` project`
https://github.com/primefaces/primevue-quickstart-vite/blob/422bae70db7cae5618a8c7e93441aed7ab7e6eb4/package.json#L10

**Comment by cagataycivici** [comment]
I'm unable to replicate, can you try with 3.3.2?
