### ISSUE TITLE
Yarn build errors for any version greater than 3.11.0

### ISSUE THREAD

**Issue by AlphaGeek** [primefaces/primevue#2500]
If we try to upgrade PrimeVue to any version greater than  3.11.0, we get the error shown below (and attached)

To upgrade, I am changing the version # in the package.json file as shown below, running "yarn" from the terminal, then running "yarn dev"

PACKAGE.JSON:

"dependencies": {
   "primeicons": "5.0.0",
    "primevue": "3.12.5",
     ... [more packages]
}

This is the scripts section in the package.json file showing what "yarn dev" does:

"scripts": {
    "serve": "vite preview",
    "build": "vite build",
    "dev": "vite --https"
  },

We are using Vite, version 2.5.10 in a Vue3, version 3.0.5, application.  

We use only Chrome (generally the latest or near latest version) on Windows 10.

Expected results, after running "yarn dev" the app builds and starts running on port 3000.

Current result using version 3.12.5 (or any version greater than 3.11.0)...running "yarn dev" produces the following build error:

error when starting dev server:
Error: Build failed with 136 errors:
node_modules/primevue/accordion/accordion.esm.js:2:20: error: No matching export in "node_modules/vue/dist/vue.esm-bundler.js" for import "createElementBlock"
node_modules/primevue/accordion/accordion.esm.js:2:62: error: No matching export in "node_modules/vue/dist/vue.esm-bundler.js" for import "normalizeClass"
node_modules/primevue/accordion/accordion.esm.js:2:78: error: No matching export in "node_modules/vue/dist/vue.esm-bundler.js" for import "createElementVNode"
node_modules/primevue/autocomplete/autocomplete.esm.js:6:56: error: No matching export in "node_modules/vue/dist/vue.esm-bundler.js" for import "createElementBlock"
node_modules/primevue/autocomplete/autocomplete.esm.js:6:76: error: No matching export in "node_modules/vue/dist/vue.esm-bundler.js" for import "normalizeClass"
...
    at failureErrorWithLog (C:\code\research\dev\client\wbresearch-client3\node_modules\esbuild\lib\main.js:1475:15)
    at C:\code\research\dev\client\wbresearch-client3\node_modules\esbuild\lib\main.js:1133:28
    at runOnEndCallbacks (C:\code\research\dev\client\wbresearch-client3\node_modules\esbuild\lib\main.js:923:63)
    at buildResponseToResult (C:\code\research\dev\client\wbresearch-client3\node_modules\esbuild\lib\main.js:1131:7)
    at C:\code\research\dev\client\wbresearch-client3\node_modules\esbuild\lib\main.js:1240:14
    at C:\code\research\dev\client\wbresearch-client3\node_modules\esbuild\lib\main.js:611:9
    at handleIncomingPacket (C:\code\research\dev\client\wbresearch-client3\node_modules\esbuild\lib\main.js:708:9)
    at Socket.readFromStdout (C:\code\research\dev\client\wbresearch-client3\node_modules\esbuild\lib\main.js:578:7)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[PrimeVue_Error.txt](https://github.com/primefaces/primevue/files/8564159/PrimeVue_Error.txt)

**Comment by tugcekucukoglu** [comment]
Do you have a repo or codesandbox link? How can I replicate the issue?
