### ISSUE TITLE
New Error when opening a Menu: TypeError: Cannot read properties of undefined (reading 'concat')

### ISSUE THREAD

**Issue by TheParad0X** [primefaces/primevue#2551]
My Menus stopped working and I am getting this error message when clicking on it:

`index.3622e95b.js:2 TypeError: Cannot read properties of undefined (reading 'concat')
    at Object.getParents (index.3622e95b.js:17:38990)
    at Object.getScrollableParents (index.3622e95b.js:17:39065)
    at ConnectedOverlayScrollHandler.bindScrollListener (index.3622e95b.js:21:1572)
    at Proxy.bindScrollListener (index.3622e95b.js:2634:6379)
    at Proxy.onEnter (index.3622e95b.js:2634:5344)
    at callHook (index.3622e95b.js:2:171729)
    at index.3622e95b.js:2:172671
    at callWithErrorHandling (index.3622e95b.js:2:113496)
    at callWithAsyncErrorHandling (index.3622e95b.js:2:113618)
    at R (index.3622e95b.js:2:125216)`

The peculiar thing is that this error only shows up with a Prod build and when served from within a Docker image.
When running locally with vite preview, the menu works as planned.

I wish I had more information regarding this error. I will update this issue as soon as I find something. 

This is my simple Menu:

```
    <Menu id="overlay_menu" ref="menu" :popup="true" :model="userActions">
      <template #item="{ item }">
          <p-button
            :icon="item.icon"
            :label="item.label"
            @click="item.command"
          ></p-button>
      </template>
    </Menu>
```

"primevue": "^3.12.6",
"vue": "^3.2.34",
"typescript": "^4.6.2",
"vite": "^2.9.9",

**Comment by TheParad0X** [comment]
I cannot reproduce this error. Todays deployment worked. I don't know what happened. Closing this and leaving it in case it happens to someone else 🤷🏻‍♂️
