### ISSUE TITLE
[Vue warn]: inject() can only be used inside setup() or functional components.

### ISSUE THREAD

**Issue by martinszeltins** [primefaces/primevue#2581]
I am getting an error when I try to use the Toast component while extracting it into a service. I don't want to call `useToast()` inside my component's `setup` but I want to extract a service for better code reuse. But in that case I am getting this error:

````
[Vue warn]: inject() can only be used inside setup() or functional components.
[Vue warn]: Unhandled error during execution of native event handler 
  at <App>

Uncaught Error: No PrimeVue Toast provided!
    at useToast (usetoast.esm.js:8:15)
    at Proxy.showToast (toastService.js:4:19)
    at _createElementVNode.onClick._cache.<computed>._cache.<computed> (App.vue:4:21)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:369:13)
````

Here is a codesandbox link: https://codesandbox.io/s/prime-vue-toast-issue-owcio8?file=/src/services/toastService.js

Here is my **main.js**

````
import App from './App.vue'
import { createApp } from 'vue'
import PrimeVue from 'primevue/config';
import 'primevue/resources/primevue.min.css';
import 'primevue/resources/themes/lara-dark-blue/theme.css';
import ToastService from 'primevue/toastservice';

const app = createApp(App);

app.use(PrimeVue);
app.use(ToastService);

app.mount('#app')
````

And here is my **App.vue**

````
<template>
    <Toast />

    <button @click="showToast">Show toast!</button>
</template>

<script setup>
    import Toast from 'primevue/toast';
    import { showToast } from './services/toastService';
</script>
````

and here is my **toastService.js:**

````
import { useToast } from "primevue/usetoast";

const showToast = () => {
    const toast = useToast();

    toast.add({ severity: 'info', detail:'Hello' });
}

export { showToast }
````

```
[x] bug report => Search github for a similar issue or PR before submitting
[ ] feature request => Please check if request is not on the roadmap already https://github.com/primefaces/primevue/wiki/Roadmap
[ ] support request => Please do not submit support request here, instead see http://forum.primefaces.org/viewforum.php?f=110
```

**CodeSandbox Case (Bug Reports)**
https://codesandbox.io/s/prime-vue-toast-issue-owcio8?file=/src/services/toastService.js

**Please tell us about your environment:**
Operating system: Ubuntu 20.04 LTS
IDE: PHPStorm
Package manager: npm
Build tool: vite.js

* **Vue version:** 3.2.25

* **PrimeVue version:** 3.12.6

**Comment by tugcekucukoglu** [comment]
[https://stackoverflow.com/questions/71883241/vue-3-inject-can-only-be-used-inside-setup-or-functional-components](https://stackoverflow.com/questions/71883241/vue-3-inject-can-only-be-used-inside-setup-or-functional-components)

**Comment by abakucz** [comment]
I would appreciate access to Toast outside of a component as well. 

For example, another UI library Element Plus solves it via [global method](https://element-plus.org/en-US/component/message.html#global-method) and it works well.

**Comment by Valar103769** [comment]
> https://stackoverflow.com/questions/71883241/vue-3-inject-can-only-be-used-inside-setup-or-functional-components

bad idea

**Comment by felipechiodini** [comment]
There is any other solution to use toast outside component?
