### ISSUE TITLE
Tooltip creates Errors in certain situations

### ISSUE THREAD

**Issue by leuprechtroman** [primefaces/primevue#2792]
### Describe the bug

We observe the case in our development environment, not in production.
Also, it seems to occur more often on route changes than on normal hovering behaviour

Sometimes the tooltip disappears but there is an error, that removing it from the body failed due to it not being a child of body:

```
tooltip.esm.js?6b8c:135 Uncaught (in promise) DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at remove (webpack-internal:///./node_modules/primevue/tooltip/tooltip.esm.js:138:27)
    at unmounted (webpack-internal:///./node_modules/primevue/tooltip/tooltip.esm.js:319:9)
    at callWithErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6829:22)
    at callWithAsyncErrorHandling (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:6838:21)
    at invokeDirectiveHook (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:3200:13)
    at Array.eval (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4870:21)
    at flushPostFlushCbs (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:7027:47)
    at flushJobs (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:7072:9)
```
After closer inspection of the code (tooltip.esm.js:135) we've noticed something strange:

```
if (tooltipElement && tooltipElement.parentElement) {
            ZIndexUtils.clear(tooltipElement);
            document.body.removeChild(tooltipElement);
        }
```
Here the code checks for the element and its parent. And then promptly ignores the checked, safe parent and calls removeChild on `document.body`.
That seems odd. Especially since the errors completely disappear, if you call `removeChild` on the checked parent like this:

```
if (tooltipElement && tooltipElement.parentElement) {
            ZIndexUtils.clear(tooltipElement);
            tooltipElement.parentElement.removeChild(tooltipElement);
        }
```

### PrimeVue version

3.15.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

### Browser(s)

Chrome 98

### Steps to reproduce the behavior

1. Create a button that changes a route
2. Apply a tooltip
3. Click on the button
4. In about 25% of the cases in our environment the error happens

### Expected behavior

There should be no error.
Also we believe the `removeChild` function should be called from the parent, as it obviously was intended to do, like this:
```
if (tooltipElement && tooltipElement.parentElement) {
            ZIndexUtils.clear(tooltipElement);
            tooltipElement.parentElement.removeChild(tooltipElement);
        }
```

**Comment by tugcekucukoglu** [comment]
Can not replicate the issue. Could you send us a codesandbox example?
