### ISSUE TITLE
Toast: Toast component not working with Nuxt 3 with composition api

### ISSUE THREAD

**Issue by david4bou** [primefaces/primevue#2984]
### Describe the bug

I have this error:
```
Uncaught Error: No PrimeVue Toast provided!
    at useToast (usetoast.esm.js:9:15)
    at Proxy.greet (index.vue:38:5)
    at _createVNode.onClick._cache.<computed>._cache.<computed> (index.vue:195:59)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:164:21)
    at HTMLButtonElement.invoker (runtime-dom.esm-bundler.js:370:13)
```

In my plugin folder I have a file named primevue-plugin.ts with this:
```
import { defineNuxtPlugin } from "#app"
import PrimeVue from "primevue/config"
import ToastService from 'primevue/toastservice';
import Toast from 'primevue/toast';

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.use(PrimeVue, {ripple: true});
    nuxtApp.vueApp.use(ToastService);
    nuxtApp.vueApp.component('Toast', Toast);
})
```

And in my pages folder I have a file named index.vue with:
```
<script lang="ts" setup>
import { useToast } from 'primevue/usetoast'

const toast = useToast()

const showSuccess = () => {
    toast.add({severity:'success', summary: 'Success Message', detail:'Message Content', life: 3000});
}
</script>

<template>
    <Toast />
    <Button label="Submit" @click="showSuccess()" />
</template>
```

I don't understand why this cause error...

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Chrome

**Comment by ian4uia** [comment]
Hi David, what version of Nuxt 3 are you using?  Using 3.0.0-rc.9 I was unable to reproduce your error and the toast popped up fine. The only thing that I have extra is that I added the following to my nuxt.config.ts  file:
```
import { defineNuxtConfig } from 'nuxt'
export default defineNuxtConfig({
  build: {
    transpile: ['primevue']
  },
  css: [
    'primevue/resources/themes/md-light-indigo/theme.css',
    'primevue/resources/primevue.min.css'
  ],
})
```
Ian

**Comment by david4bou** [comment]
> 

Hi, I'm using 3.0.0-rc.9 and I have the same nuxt.config.ts.

**Comment by trizotti** [comment]
I tried to reproduce this error too, but the toast works just fine. @david4bou, maybe with a reproducer would be easier to find out what's happening...

**Comment by david4bou** [comment]
I tried too and now, the toast works fine too. Idk
