### ISSUE TITLE
OverlayPanel: open after await promise

### ISSUE THREAD

**Issue by Rakasch** [primefaces/primevue#3164]
### Describe the bug

TypeError: Cannot read properties of null (reading 'offsetHeight')
 at Object.absolutePosition (utils.esm.js:213:44)
 at Proxy.alignOverlay (overlaypanel.esm.js:151:24)

I need to load data and wait for the data to be loaded before displaying the overlaypanel.
Therefore I open the overlaypanel in the resolved promise.
"Test 1" is only for demonstrating my motivation.
"Test 2" throws the acutal error.

### Reproducer

https://codesandbox.io/s/small-feather-nw4tkh?file=/src/OverlayPanelDemo.vue

### PrimeVue version

3.17.0

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. go to reproducer link
https://codesandbox.io/s/small-feather-nw4tkh?file=/src/OverlayPanelDemo.vue
2. click on "Test 2"

### Expected behavior

open the Overlaypanel on Test 2.

**Comment by bahadirsofuoglu** [comment]
We provide target parameter for these cases. For example: 
`
<Button ref="buttonref" type="button" icon="pi pi-search" :label="selectedProduct ? selectedProduct.name : 'Select a Product'" @click="toggle" aria-haspopup="true" aria-controls="overlay_panel" />
this.$refs.op.toggle(event, this.$refs.buttonref.$el)
`

**Comment by bahadirsofuoglu** [comment]
You can use toggle method. Type definition mistake. We will add to the next release

**Comment by tugcekucukoglu** [comment]
Event bubbling causes that problem. You could find more info about this https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget

In this case, https://github.com/primefaces/primevue/issues/3164#issuecomment-1292033844 is the best practise. Thanks @bahadirsofuoglu

**Comment by Oli8** [comment]
Same issue but with `Menu` used as popup

Using show/toggle with a ref on the opener didn't fix it
