### ISSUE TITLE
Dropdown:  TypeError: this.visibleOptions.findIndex is not a function

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#3347]
### Describe the bug

Uncaught (in promise) TypeError: this.visibleOptions.findIndex is not a function
    at Proxy.findSelectedOptionIndex (dropdown.esm.js:674:1)
    at Proxy.label (dropdown.esm.js:841:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:187:1)
    at get value [as value] (reactivity.esm-bundler.js:1150:1)
    at Object.get [as label] (runtime-core.esm-bundler.js:3470:1)
    at Object.get (runtime-core.esm-bundler.js:3138:1)
    at Proxy.inputStyleClass (dropdown.esm.js:795:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js:187:1)
    at get value [as value] (reactivity.esm-bundler.js:1150:1)
    at Object.get [as inputStyleClass] (runtime-core.esm-bundler.js:3470:1)

in 

 findSelectedOptionIndex() {
            return this.hasSelectedOption ? this.visibleOptions.findIndex((option) => this.isValidSelectedOption(option)) : -1;
},

![image](https://user-images.githubusercontent.com/16963395/204730372-82bba615-37c0-48ae-9b1a-3f4ac52c8e74.png)

![image](https://user-images.githubusercontent.com/16963395/204730298-56b0342d-432c-4385-99ea-26b355f5fe98.png)

![image](https://user-images.githubusercontent.com/16963395/204730546-1b9ec8a7-c88d-4034-8fec-7ef937102eba.png)

### Reproducer

no

### PrimeVue version

3.20.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by mertsincan** [comment]
Hi @NeluQi, 

Unfortunately, I couldn't replicate it. How can I replicate it? We use visibleOptions value everywhere, so if you can give more details, I can come up with a general solution instead of a null check. Also, which of the following returns null or undefined instead of an empty array? could you please debug these lines?
```
...
        visibleOptions() {
            ...

                    return this.flatOptions(filtered);
                }

                return filteredOptions;
            }

            return options;
        },
...
```

**Comment by NeluQi** [comment]
> Hi @NeluQi,
> 
> Unfortunately, I couldn't replicate it. How can I replicate it? We use visibleOptions value everywhere, so if you can give more details, I can come up with a general solution instead of a null check. Also, which of the following returns null or undefined instead of an empty array? could you please debug these lines?
> 
> ```
> ...
>         visibleOptions() {
>             ...
> 
>                     return this.flatOptions(filtered);
>                 }
> 
>                 return filteredOptions;
>             }
> 
>             return options;
>         },
> ...
> ```

It doesn't seem to happen anymore, maybe it's a one-time error

If it works, I'll post the procedure.

**Comment by mertsincan** [comment]
Ok, thanks a lot for the update!

**Comment by Azzammi** [comment]
Hi, i encounter the same thing

dropdown.esm.js?a2ed:688 Uncaught (in promise) TypeError: this.visibleOptions.findIndex is not a function
    at Proxy.findSelectedOptionIndex (dropdown.esm.js?a2ed:688:1)
    at Proxy.label (dropdown.esm.js?a2ed:855:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js?89dc:190:1)
    at get value [as value] (reactivity.esm-bundler.js?89dc:1171:1)
    at Object.get [as label] (runtime-core.esm-bundler.js?d2dd:3488:1)
    at Object.get (runtime-core.esm-bundler.js?d2dd:3156:1)
    at Proxy.inputStyleClass (dropdown.esm.js?a2ed:809:1)
    at ReactiveEffect.run (reactivity.esm-bundler.js?89dc:190:1)
    at get value [as value] (reactivity.esm-bundler.js?89dc:1171:1)
    at Object.get [as inputStyleClass] (runtime-core.esm-bundler.js?d2dd:3488:1)
    
![image](https://user-images.githubusercontent.com/23116326/227753649-70f1b9fc-837a-4e1a-9fe7-93091f06e6ce.png)

### Reproducer
no

### PrimeVue version
3.26.0

### Vue version
3.x

### Language
Javascript

### Build / Runtime
Webpack CLI with laravel mix

### Browser(s)
Blank White

### Steps to reproduce the behavior
- npm run watch
- open page with dropdown component on it

### Expected behavior
page opened

**Comment by tugcekucukoglu** [comment]
Please try to use with the latest version. If the problem still persists, please create a new with a reproducer link.

**Comment by dejudicibus** [comment]
Same problem

`Uncaught runtime errors:
×
ERROR
this.visibleOptions.filter is not a function
TypeError: this.visibleOptions.filter is not a function
    at Proxy.ariaSetSize (webpack-internal:///./node_modules/primevue/dropdown/dropdown.esm.js:1042:34)
    at ReactiveEffect.eval [as fn] (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:958:44)
    at ReactiveEffect.run (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:217:19)
    at get value (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:965:147)
    at Object.get [as ariaSetSize] (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:3279:22)
    at eval (webpack-internal:///./node_modules/primevue/dropdown/dropdown.esm.js:1384:44)
    at renderList (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:2711:18)
    at eval (webpack-internal:///./node_modules/primevue/dropdown/dropdown.esm.js:1352:249)
    at renderFnWithContext (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:886:13)
    at renderSlot (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:2753:53)`

**Comment by Beadko** [comment]
Same issue here. Using the latest primevue version. Using a Select component
chunk-LSP4XMBO.js?v=f16c500f:2024 Uncaught (in promise) TypeError: this.visibleOptions.findIndex is not a function
    at Proxy.findSelectedOptionIndex (chunk-LSP4XMBO.js?v=f16c500f:2024:59)
    at Proxy.label2 (chunk-LSP4XMBO.js?v=f16c500f:2163:38)
    at ReactiveEffect.fn (chunk-C4KGUF5A.js?v=f16c500f:1248:13)
    at ReactiveEffect.run (chunk-C4KGUF5A.js?v=f16c500f:436:19)
    at get value (chunk-C4KGUF5A.js?v=f16c500f:1260:107)
    at Object.get [as label] (chunk-C4KGUF5A.js?v=f16c500f:4117:22)
    at Object.get (chunk-C4KGUF5A.js?v=f16c500f:3661:23)
    at label (chunk-LSP4XMBO.js?v=f16c500f:1170:52)
    at Object.getItemValue2 [as getItemValue] (chunk-W2667YSA.js?v=f16c500f:2235:39)
    at Proxy._getOptionValue (chunk-2G5AXICM.js?v=f16c500f:334:86)

**Comment by FelipeAzambuja** [comment]
Same problem
`
dropdown.esm.js?v=8f05df4d:776 Uncaught (in promise) TypeError: this.visibleOptions.findIndex is not a function
    at Proxy.findSelectedOptionIndex (dropdown.esm.js?v=8f05df4d:776:59)
    at Proxy.updated (dropdown.esm.js?v=8f05df4d:257:30)
    at runtime-core.esm-bundler.js?v=8f05df4d:2841:40
    at callWithErrorHandling (runtime-core.esm-bundler.js?v=8f05df4d:197:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?v=8f05df4d:204:17)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js?v=8f05df4d:2821:19)
    at flushPostFlushCbs (runtime-core.esm-bundler.js?v=8f05df4d:382:28)
    at flushJobs (runtime-core.esm-bundler.js?v=8f05df4d:424:5)
`

**Comment by FelipeAzambuja** [comment]
Same problem
dropdown.esm.js?v=8f05df4d:776 Uncaught (in promise) TypeError: this.visibleOptions.findIndex is not a function at Proxy.findSelectedOptionIndex (dropdown.esm.js?v=8f05df4d:776:59) at Proxy.updated (dropdown.esm.js?v=8f05df4d:257:30) at runtime-core.esm-bundler.js?v=8f05df4d:2841:40 at callWithErrorHandling (runtime-core.esm-bundler.js?v=8f05df4d:197:19) at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?v=8f05df4d:204:17) at hook.__weh.hook.__weh (runtime-core.esm-bundler.js?v=8f05df4d:2821:19) at flushPostFlushCbs (runtime-core.esm-bundler.js?v=8f05df4d:382:28) at flushJobs (runtime-core.esm-bundler.js?v=8f05df4d:424:5)

**Comment by FelipeAzambuja** [comment]
> Same problem dropdown.esm.js?v=8f05df4d:776 Uncaught (in promise) TypeError: this.visibleOptions.findIndex is not a function at Proxy.findSelectedOptionIndex (dropdown.esm.js?v=8f05df4d:776:59) at Proxy.updated (dropdown.esm.js?v=8f05df4d:257:30) at runtime-core.esm-bundler.js?v=8f05df4d:2841:40 at callWithErrorHandling (runtime-core.esm-bundler.js?v=8f05df4d:197:19) at callWithAsyncErrorHandling (runtime-core.esm-bundler.js?v=8f05df4d:204:17) at hook.__weh.hook.__weh (runtime-core.esm-bundler.js?v=8f05df4d:2821:19) at flushPostFlushCbs (runtime-core.esm-bundler.js?v=8f05df4d:382:28) at flushJobs (runtime-core.esm-bundler.js?v=8f05df4d:424:5)

i get this bug using a collect.js object not a vanilla array
