### ISSUE TITLE
Component Name: FileUpload function error: onRemoveTemplatingFile

### ISSUE THREAD

**Issue by wcf1997** [primefaces/primevue#3630]
### Describe the bug

entry.7d7c0a28.js:1 TypeError: a is not a function
    at Proxy.onRemoveTemplatingFile (index.3ec49a9a.js:1:410)
    at onClick (index.3ec49a9a.js:1:4566)
    at zo (entry.7d7c0a28.js:1:12229)
    at Ws (entry.7d7c0a28.js:1:12308)
    at HTMLButtonElement.i (entry.7d7c0a28.js:1:66644)

### Reproducer

https://codesandbox.io/embed/elated-montalcini-ggj0x7?fontsize=14&hidenavigation=1&theme=dark

### PrimeVue version

3.21.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by bahadirsofuoglu** [comment]
Hi, Content slot does not have a callback named fileRemoveCallback.
