### ISSUE TITLE
Rating does not work: Cannot read properties of undefined (reading 'star')

### ISSUE THREAD

**Issue by TheParad0X** [primefaces/primevue#3654]
### Describe the bug

As soon as I use the Rating, the following Error appears:

`TypeError: Cannot read properties of undefined (reading 'star')
    at Proxy.starAriaLabel (rating.esm.js:87:68)
    at rating.esm.js:163:36
    at renderList (runtime-core.esm-bundler.js:2939:22)
    at Proxy.render (rating.esm.js:149:58)
    at renderComponentRoot (runtime-core.esm-bundler.js:914:44)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5649:57)
    at ReactiveEffect.run (reactivity.esm-bundler.js:190:25)
    at instance.update (runtime-core.esm-bundler.js:5763:56)
    at setupRenderEffect (runtime-core.esm-bundler.js:5777:9)
    at mountComponent (runtime-core.esm-bundler.js:5559:9)`

My vue App:

```
<template>
    <Rating modelValue="2" />
</template>

<script setup>
import Rating from 'primevue/rating';
</script>
```

I dont' know why, but the Reproducer works as intended (however when I click on "Save", the import of the Rating component does not work anymore) - but it only works when specifying 

`app.component("Rating", Rating);`

in main.js

### Reproducer

https://codesandbox.io/s/determined-stallman-bzpkoe?file=/src/main.js

### PrimeVue version

3.23.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

Use the Rating component

### Expected behavior

No error 🤷‍♂️

**Comment by TheParad0X** [comment]
So the inner error message seems to suggest that a primevue is looking for a "start" variable in the config:

`        starAriaLabel(value) {
            return value === 1 ? this.$primevue.config.locale.aria.star : this.$primevue.config.locale.aria.stars.replace(/{star}/g, value);
        }`

So by adding this in main.js:

`app.use(PrimeVue, {
  locale: {
    aria: {
      stars: '',
    },
}`

the error disappears. Still, this cannot be the preferred Workaround, can it? 🤔

**Comment by TheParad0X** [comment]
OK so this explains it: https://primevue.org/locale 😅
