### ISSUE TITLE
DataTable: frozen error

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#3948]
### Describe the bug

![image](https://github.com/primefaces/primevue/assets/16963395/71408f7c-bab7-4112-b7d8-def1d4ea79a1)

![image](https://github.com/primefaces/primevue/assets/16963395/7242521a-a261-4c0f-aaaa-a433e2dfe9c7)
tatable.esm.js:2734 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'style')
    at Proxy.updateStickyPosition (datatable.esm.js:2734:1)
    at Proxy.mounted (datatable.esm.js:2652:1)
    at runtime-core.esm-bundler.js:2757:1
    at callWithErrorHandling (runtime-core.esm-bundler.js:173:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:182:1)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2731:1)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:359:1)
    at flushJobs (runtime-core.esm-bundler.js:413:1)
u

![image](https://github.com/primefaces/primevue/assets/16963395/3628b50d-ddfb-4676-a026-7db0260b0eb5)

![image](https://github.com/primefaces/primevue/assets/16963395/4dacda0a-864e-4464-a506-109af97269ab)

updateStickyPosition is error

### Reproducer

no

### PrimeVue version

3.28.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by ohadtz** [comment]
this happens to me as well
