### ISSUE TITLE
datatable: TypeError: Cannot read properties of undefined (reading 'style')

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#4215]
### Describe the bug

frozen + no column = error

pls add null check in updateStickyPosition

datatable.esm.js:3478 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'style')
    at Proxy.updateStickyPosition (datatable.esm.js:3478:1)
    at Proxy.mounted (datatable.esm.js:3370:1)
    at runtime-core.esm-bundler.js:2675:1
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:1)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2655:1)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:325:1)
    at flushJobs (runtime-core.esm-bundler.js:363:1)

![image](https://github.com/primefaces/primevue/assets/16963395/41af1c70-98e9-4f60-83d9-8eb45aa269ad)

### Reproducer

no

### PrimeVue version

3.23.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by ohadtz** [comment]
happens to me as well
