### ISSUE TITLE
DataTable: Computed property "getPTOptions" is already defined in Methods. 

### ISSUE THREAD

**Issue by NeluQi** [primefaces/primevue#4745]
### Describe the bug

![image](https://github.com/primefaces/primevue/assets/16963395/88ac77f8-e62d-4c21-96cc-f3d9af172947)
runtime-core.esm-bundler.js:41 [Vue warn]: Computed property "getPTOptions" is already defined in Methods. 
  at <FirstPageLink key=0 aria-label="First Page" template=undefined  ... > 
  at <Paginator key=4 rows=20 first=0  ... > 
  at <DataTable ref="dt" editingRows= [] onUpdate:editingRows=fn  ... > 
  at <ScrollPanel style= {width: '100%', height: '520px'} > 
  at <DictionaryProject project-id=28 > 

### Reproducer

no

### PrimeVue version

last

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vue CLI App

**Comment by tugcekucukoglu** [comment]
Could you tell us your environment?

**Comment by NeluQi** [comment]
Vue3 + vite + ionic + primevue

**Comment by skamansam** [comment]
I am getting the same issue with TieredMenu. Really, splitterpanel keeps throwing this error, in different, seemingly random, times. Sometimes it is with checkbox, sometimes, it is with other components. I am using a 3-way split panel and a tiered menu that is NOT in the splitterpanel. I have tried repeatedly to create a reproduction repo for this error, but can't. 

```
splitterpanel.esm.js:31 Uncaught (in promise) TypeError: this.$slots.default is not a function
    at Proxy.isNested (splitterpanel.esm.js:31:35)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at get value [as value] (reactivity.esm-bundler.js:1135:33)
    at Object.get [as isNested] (runtime-core.esm-bundler.js:3418:22)
    at Object.get (runtime-core.esm-bundler.js:2942:16)
    at Proxy.getPTOptions (splitterpanel.esm.js:38:24)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at get value [as value] (reactivity.esm-bundler.js:1135:33)
    at Object.get [as getPTOptions] (runtime-core.esm-bundler.js:3418:22)
    at tieredmenu.esm.js:234:17
```

```
splitterpanel.esm.js:31 Uncaught (in promise) TypeError: this.$slots.default is not a function
    at Proxy.isNested (splitterpanel.esm.js:31:35)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at get value [as value] (reactivity.esm-bundler.js:1135:33)
    at Object.get [as isNested] (runtime-core.esm-bundler.js:3418:22)
    at Object.get (runtime-core.esm-bundler.js:2942:16)
    at Proxy.getPTOptions (splitterpanel.esm.js:38:24)
    at ReactiveEffect.run (reactivity.esm-bundler.js:178:19)
    at get value [as value] (reactivity.esm-bundler.js:1135:33)
    at Object.get [as getPTOptions] (runtime-core.esm-bundler.js:3418:22)
    at Proxy.render (checkbox.esm.js:152:15)
```

After i get the error, i can't activate the tieredmenu any more, regardless of where the error comes from. 

Here is a related warning I am getting in the console, as well:

```
[Vue warn]: Computed property "getPTOptions" is already defined in Methods. 
  at <Checkbox id="fitted" name="terms" value="fitted"  ... > 
  at <RenderFnWithContext key=1 data="fitted" column= 
{__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …}
  ... > 
  at <BodyCell key="term" rowData="fitted" column= 
{__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …}
  ... > 
  at <TableBody ref="bodyRef" value= 
(5) ['fitted', 'ear', 'grease', 'in', 'edge']
 class=""  ... > 
  at <VirtualScroller ref="virtualScroller" items= 
(5) ['fitted', 'ear', 'grease', 'in', 'edge']
 columns= 
(3) [{…}, {…}, {…}]
  ... > 
  at <DataTable value= 
(5) ['fitted', 'ear', 'grease', 'in', 'edge']
 paginator=true rows=5  ... > 
  at <SimilarTermsPanelInlineEditing term= 
{key: 'replace-Solution-synonym', tags: 'synonym (replaced,repalced)', tagData: Proxy(Array), classification: 'Solution', notes: ' ', …}
 ngramType="unigrams" > 
  at <SplitterPanel key=0 minSize=20 size=20  ... > 
  at <Splitter style= 
{height: 'calc(100vh - 200px) !important'}
 layout="vertical" class="h-full surface-ground border-none"  ... > 
  at <SplitterPanel key=2 minSize=20 size=20  ... > 
  at <Splitter style= 
{height: 'calc(100vh - 200px) !important'}
 class="h-full surface-ground border-none" stateKey="worspaceState"  ... > 
  at <Workspace datasetSlug="excavator-100" ngram="unigrams" onVnodeUnmounted=fn<onVnodeUnmounted>  ... > 
  at <RouterView> 
  at <ENTer Main App>
warn2	@	runtime-core.esm-bundler.js:41
(anonymous)	@	runtime-core.esm-bundler.js:3283
applyOptions	@	runtime-core.esm-bundler.js:3422
finishComponentSetup	@	runtime-core.esm-bundler.js:7395
setupStatefulComponent	@	runtime-core.esm-bundler.js:7318
setupComponent	@	runtime-core.esm-bundler.js:7250
mountComponent	@	runtime-core.esm-bundler.js:5646
processComponent	@	runtime-core.esm-bundler.js:5612
patch	@	runtime-core.esm-bundler.js:5087
mountChildren	@	runtime-core.esm-bundler.js:5331
processFragment	@	runtime-core.esm-bundler.js:5546
patch	@	runtime-core.esm-bundler.js:5061
componentUpdateFn	@	runtime-core.esm-bundler.js:5755
run	@	reactivity.esm-bundler.js:178
instance.update	@	runtime-core.esm-bundler.js:5861
setupRenderEffect	@	runtime-core.esm-bundler.js:5869
mountComponent	@	runtime-core.esm-bundler.js:5659
processComponent	@	runtime-core.esm-bundler.js:5612
patch	@	runtime-core.esm-bundler.js:5087
mountChildren	@	runtime-core.esm-bundler.js:5331
mountElement	@	runtime-core.esm-bundler.js:5238
processElement	@	runtime-core.esm-bundler.js:5203
patch	@	runtime-core.esm-bundler.js:5075
componentUpdateFn	@	runtime-core.esm-bundler.js:5755
run	@	reactivity.esm-bundler.js:178
instance.update	@	runtime-core.esm-bundler.js:5861
setupRenderEffect	@	runtime-core.esm-bundler.js:5869
mountComponent	@	runtime-core.esm-bundler.js:5659
processComponent	@	runtime-core.esm-bundler.js:5612
patch	@	runtime-core.esm-bundler.js:5087
mountChildren	@	runtime-core.esm-bundler.js:5331
processFragment	@	runtime-core.esm-bundler.js:5546
patch	@	runtime-core.esm-bundler.js:5061
mountChildren	@	runtime-core.esm-bundler.js:5331
processFragment	@	runtime-core.esm-bundler.js:5546
patch	@	runtime-core.esm-bundler.js:5061
mountChildren	@	runtime-core.esm-bundler.js:5331
mountElement	@	runtime-core.esm-bundler.js:5238
processElement	@	runtime-core.esm-bundler.js:5203
patch	@	runtime-core.esm-bundler.js:5075
mountChildren	@	runtime-core.esm-bundler.js:5331
processFragment	@	runtime-core.esm-bundler.js:5546
patch	@	runtime-core.esm-bundler.js:5061
mountChildren	@	runtime-core.esm-bundler.js:5331
processFragment	@	runtime-core.esm-bundler.js:5546
patch	@	runtime-core.esm-bundler.js:5061
patchBlockChildren	@	runtime-core.esm-bundler.js:5474
patchElement	@	runtime-core.esm-bundler.js:5366
processElement	@	runtime-core.esm-bundler.js:5214
patch	@	runtime-core.esm-bundler.js:5075
componentUpdateFn	@	runtime-core.esm-bundler.js:5820
run	@	reactivity.esm-bundler.js:178
instance.update	@	runtime-core.esm-bundler.js:5861
updateComponent	@	runtime-core.esm-bundler.js:5688
processComponent	@	runtime-core.esm-bundler.js:5623
patch	@	runtime-core.esm-bundler.js:5087
patchBlockChildren	@	runtime-core.esm-bundler.js:5474
processFragment	@	runtime-core.esm-bundler.js:5560
patch	@	runtime-core.esm-bundler.js:5061
patchBlockChildren	@	runtime-core.esm-bundler.js:5474
processFragment	@	runtime-core.esm-bundler.js:5560
patch	@	runtime-core.esm-bundler.js:5061
componentUpdateFn	@	runtime-core.esm-bundler.js:5820
run	@	reactivity.esm-bundler.js:178
instance.update	@	runtime-core.esm-bundler.js:5861
updateComponent	@	runtime-core.esm-bundler.js:5688
processComponent	@	runtime-core.esm-bundler.js:5623
patch	@	runtime-core.esm-bundler.js:5087
patchBlockChildren	@	runtime-core.esm-bundler.js:5474
patchElement	@	runtime-core.esm-bundler.js:5366
processElement	@	runtime-core.esm-bundler.js:5214
patch	@	runtime-core.esm-bundler.js:5075
componentUpdateFn	@	runtime-core.esm-bundler.js:5820
run	@	reactivity.esm-bundler.js:178
instance.update	@	runtime-core.esm-bundler.js:5861
updateComponent	@	runtime-core.esm-bundler.js:5688
processComponent	@	runtime-core.esm-bundler.js:5623
patch	@	runtime-core.esm-bundler.js:5087
patchKeyedChildren	@	runtime-core.esm-bundler.js:6012
patchChildren	@	runtime-core.esm-bundler.js:5926
patchElement	@	runtime-core.esm-bundler.js:5379
processElement	@	runtime-core.esm-bundler.js:5214
patch	@	runtime-core.esm-bundler.js:5075
patchKeyedChildren	@	runtime-core.esm-bundler.js:6012
patchChildren	@	runtime-core.esm-bundler.js:5926
processFragment	@	runtime-core.esm-bundler.js:5586
patch	@	runtime-core.esm-bundler.js:5061
componentUpdateFn	@	runtime-core.esm-bundler.js:5820
run	@	reactivity.esm-bundler.js:178
instance.update	@	runtime-core.esm-bundler.js:5861
callWithErrorHandling	@	runtime-core.esm-bundler.js:158
flushJobs	@	runtime-core.esm-bundler.js:362
Promise.then (async)		
queueFlush	@	runtime-core.esm-bundler.js:275
queueJob	@	runtime-core.esm-bundler.js:269
(anonymous)	@	runtime-core.esm-bundler.js:5857
triggerEffect	@	reactivity.esm-bundler.js:373
triggerEffects	@	reactivity.esm-bundler.js:363
trigger	@	reactivity.esm-bundler.js:335
set	@	reactivity.esm-bundler.js:489
set	@	runtime-core.esm-bundler.js:2997
setSimilarTerms	@	SimilarTermsPanelInlineEditing.vue:75
```
There are more warnings as well:

```
SimilarTermsPanelInlineEditing.vue:75 [Vue warn]: Unhandled error during execution of render function 
  at <Checkbox id="fitted" name="terms" value="fitted"  ... > 
  at <RenderFnWithContext key=1 data="fitted" column= {__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …}  ... > 
  at <BodyCell key="term" rowData="fitted" column= {__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …}  ... > 
  at <TableBody ref="bodyRef" value= (5) ['fitted', 'ear', 'grease', 'in', 'edge'] class=""  ... > 
  at <VirtualScroller ref="virtualScroller" items= (5) ['fitted', 'ear', 'grease', 'in', 'edge'] columns= (3) [{…}, {…}, {…}]  ... > 
  at <DataTable value= (5) ['fitted', 'ear', 'grease', 'in', 'edge'] paginator=true rows=5  ... > 
  at <SimilarTermsPanelInlineEditing term= {key: 'replace-Solution-synonym', tags: 'synonym (replaced,repalced)', tagData: Proxy(Array), classification: 'Solution', notes: ' ', …} ngramType="unigrams" > 
  at <SplitterPanel key=0 minSize=20 size=20  ... > 
  at <Splitter style= {height: 'calc(100vh - 200px) !important'} layout="vertical" class="h-full surface-ground border-none"  ... > 
  at <SplitterPanel key=2 minSize=20 size=20  ... > 
  at <Splitter style= {height: 'calc(100vh - 200px) !important'} class="h-full surface-ground border-none" stateKey="worspaceState"  ... > 
  at <Workspace datasetSlug="excavator-100" ngram="unigrams" onVnodeUnmounted=fn<onVnodeUnmounted>  ... > 
  at <RouterView> 
  at <ENTer Main App>
warn2 @ runtime-core.esm-bundler.js:41
logError @ runtime-core.esm-bundler.js:216
handleError @ runtime-core.esm-bundler.js:208
renderComponentRoot @ runtime-core.esm-bundler.js:858
componentUpdateFn @ runtime-core.esm-bundler.js:5748
run @ reactivity.esm-bundler.js:178
instance.update @ runtime-core.esm-bundler.js:5861
setupRenderEffect @ runtime-core.esm-bundler.js:5869
mountComponent @ runtime-core.esm-bundler.js:5659
processComponent @ runtime-core.esm-bundler.js:5612
patch @ runtime-core.esm-bundler.js:5087
mountChildren @ runtime-core.esm-bundler.js:5331
processFragment @ runtime-core.esm-bundler.js:5546
patch @ runtime-core.esm-bundler.js:5061
componentUpdateFn @ runtime-core.esm-bundler.js:5755
run @ reactivity.esm-bundler.js:178
instance.update @ runtime-core.esm-bundler.js:5861
setupRenderEffect @ runtime-core.esm-bundler.js:5869
mountComponent @ runtime-core.esm-bundler.js:5659
processComponent @ runtime-core.esm-bundler.js:5612
patch @ runtime-core.esm-bundler.js:5087
mountChildren @ runtime-core.esm-bundler.js:5331
mountElement @ runtime-core.esm-bundler.js:5238
processElement @ runtime-core.esm-bundler.js:5203
patch @ runtime-core.esm-bundler.js:5075
componentUpdateFn @ runtime-core.esm-bundler.js:5755
run @ reactivity.esm-bundler.js:178
instance.update @ runtime-core.esm-bundler.js:5861
setupRenderEffect @ runtime-core.esm-bundler.js:5869
mountComponent @ runtime-core.esm-bundler.js:5659
processComponent @ runtime-core.esm-bundler.js:5612
patch @ runtime-core.esm-bundler.js:5087
mountChildren @ runtime-core.esm-bundler.js:5331
processFragment @ runtime-core.esm-bundler.js:5546
patch @ runtime-core.esm-bundler.js:5061
mountChildren @ runtime-core.esm-bundler.js:5331
processFragment @ runtime-core.esm-bundler.js:5546
patch @ runtime-core.esm-bundler.js:5061
mountChildren @ runtime-core.esm-bundler.js:5331
mountElement @ runtime-core.esm-bundler.js:5238
processElement @ runtime-core.esm-bundler.js:5203
patch @ runtime-core.esm-bundler.js:5075
mountChildren @ runtime-core.esm-bundler.js:5331
processFragment @ runtime-core.esm-bundler.js:5546
patch @ runtime-core.esm-bundler.js:5061
mountChildren @ runtime-core.esm-bundler.js:5331
processFragment @ runtime-core.esm-bundler.js:5546
patch @ runtime-core.esm-bundler.js:5061
patchBlockChildren @ runtime-core.esm-bundler.js:5474
patchElement @ runtime-core.esm-bundler.js:5366
processElement @ runtime-core.esm-bundler.js:5214
patch @ runtime-core.esm-bundler.js:5075
componentUpdateFn @ runtime-core.esm-bundler.js:5820
run @ reactivity.esm-bundler.js:178
instance.update @ runtime-core.esm-bundler.js:5861
updateComponent @ runtime-core.esm-bundler.js:5688
processComponent @ runtime-core.esm-bundler.js:5623
patch @ runtime-core.esm-bundler.js:5087
patchBlockChildren @ runtime-core.esm-bundler.js:5474
processFragment @ runtime-core.esm-bundler.js:5560
patch @ runtime-core.esm-bundler.js:5061
patchBlockChildren @ runtime-core.esm-bundler.js:5474
processFragment @ runtime-core.esm-bundler.js:5560
patch @ runtime-core.esm-bundler.js:5061
componentUpdateFn @ runtime-core.esm-bundler.js:5820
run @ reactivity.esm-bundler.js:178
instance.update @ runtime-core.esm-bundler.js:5861
updateComponent @ runtime-core.esm-bundler.js:5688
processComponent @ runtime-core.esm-bundler.js:5623
patch @ runtime-core.esm-bundler.js:5087
patchBlockChildren @ runtime-core.esm-bundler.js:5474
patchElement @ runtime-core.esm-bundler.js:5366
processElement @ runtime-core.esm-bundler.js:5214
patch @ runtime-core.esm-bundler.js:5075
componentUpdateFn @ runtime-core.esm-bundler.js:5820
run @ reactivity.esm-bundler.js:178
instance.update @ runtime-core.esm-bundler.js:5861
updateComponent @ runtime-core.esm-bundler.js:5688
processComponent @ runtime-core.esm-bundler.js:5623
patch @ runtime-core.esm-bundler.js:5087
patchKeyedChildren @ runtime-core.esm-bundler.js:6012
patchChildren @ runtime-core.esm-bundler.js:5926
patchElement @ runtime-core.esm-bundler.js:5379
processElement @ runtime-core.esm-bundler.js:5214
patch @ runtime-core.esm-bundler.js:5075
patchKeyedChildren @ runtime-core.esm-bundler.js:6012
patchChildren @ runtime-core.esm-bundler.js:5926
processFragment @ runtime-core.esm-bundler.js:5586
patch @ runtime-core.esm-bundler.js:5061
componentUpdateFn @ runtime-core.esm-bundler.js:5820
run @ reactivity.esm-bundler.js:178
instance.update @ runtime-core.esm-bundler.js:5861
callWithErrorHandling @ runtime-core.esm-bundler.js:158
flushJobs @ runtime-core.esm-bundler.js:362
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:275
queueJob @ runtime-core.esm-bundler.js:269
(anonymous) @ runtime-core.esm-bundler.js:5857
triggerEffect @ reactivity.esm-bundler.js:373
triggerEffects @ reactivity.esm-bundler.js:363
trigger @ reactivity.esm-bundler.js:335
set @ reactivity.esm-bundler.js:489
set @ runtime-core.esm-bundler.js:2997
setSimilarTerms @ SimilarTermsPanelInlineEditing.vue:75
Show 102 more frames
```


and 
```
[Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug. Please open an issue at https://new-issue.vuejs.org/?repo=vuejs/core 
  at <Checkbox id="fitted" name="terms" value="fitted"  ... > 
  at <RenderFnWithContext key=1 data="fitted" column= {__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …}  ... > 
  at <BodyCell key="term" rowData="fitted" column= {__v_isVNode: true, __v_skip: true, type: {…}, props: {…}, key: null, …}  ... > 
  at <TableBody ref="bodyRef" value= (5) ['fitted', 'ear', 'grease', 'in', 'edge'] class=""  ... > 
  at <VirtualScroller ref="virtualScroller" items= (5) ['fitted', 'ear', 'grease', 'in', 'edge'] columns= (3) [{…}, {…}, {…}]  ... > 
  at <DataTable value= (5) ['fitted', 'ear', 'grease', 'in', 'edge'] paginator=true rows=5  ... > 
  at <SimilarTermsPanelInlineEditing term= {key: 'replace-Solution-synonym', tags: 'synonym (replaced,repalced)', tagData: Proxy(Array), classification: 'Solution', notes: ' ', …} ngramType="unigrams" > 
  at <SplitterPanel key=0 minSize=20 size=20  ... > 
  at <Splitter style= {height: 'calc(100vh - 200px) !important'} layout="vertical" class="h-full surface-ground border-none"  ... > 
  at <SplitterPanel key=2 minSize=20 size=20  ... > 
  at <Splitter style= {height: 'calc(100vh - 200px) !important'} class="h-full surface-ground border-none" stateKey="worspaceState"  ... > 
  at <Workspace datasetSlug="excavator-100" ngram="unigrams" onVnodeUnmounted=fn<onVnodeUnmounted>  ... > 
  at <RouterView> 
  at <ENTer Main App>
```

**Comment by Rakasch** [comment]
I remember I also encountered that message "Computed property "getPTOptions" is already defined in Methods" from time to time. I also encountered the "TypeError: this.$slots.default is not a function" error from the splitter. Although I couldn't say for sure, if those were related to each other.
After reloading and/or restarting vite it went away for some time, to show up again randomly later again.
I just assumed it to be related with the hot reloading and ignored it.

**Comment by Kotoriii** [comment]
Similar issue: https://github.com/primefaces/primevue/issues/4924

**Comment by mertsincan** [comment]
Interesting! Unfortunately, I couldn't replicate it. Could you please attach a sample project/stackblitz link to replicate it?

**Comment by mertsincan** [comment]
For now, closed. If a new update comes from your side, please reopen this ticket. Thanks a lot for your understanding!

**Comment by LiamAird** [comment]
I still get this error - with version 3.46.0.
Setup is vue3, webpack and primevue.

It happens when using the DataTable in one or more routes. 

Route 1 has a DataTable
Route 2 has a DataTable

Navigating from 1 > 2 does nothing, navigating back from 2 > 1 shows all the warnings. 
It seems to happen if you have tables with more than 1 item on both the routes. 

```
[Vue warn]: Computed property "bodyStyle" is already defined in Props. 
  at <Column key=4 field="field1" sortable="" > 
  at <DataTable scrollable="" scrollHeight="600px" expandedRows=null  ... > 
```
```
[Vue warn]: Computed property "field" is already defined in Props. 
  at <Column key=5 field="field2" sortable="" > 
```

```
<DataTable
	scrollable
	scrollHeight="600px"

	v-model:expandedRows="expandedRows"
	dataKey="market"

	resizableColumns
	columnResizeMode="fit"

	v-model:filters="filters"

	:value="computedResults"
	size="small"
	stripedRows

	:rowClass="rowClass"

	removableSort
	sortField="profit"
	:sortOrder="-1"

	:loading="loading"
	tableStyle="min-width: 50rem"
	:globalFilterFields="['market']"
>
```

```
<Column
	v-if="selected.includes('field1')"
	field="field1"
	sortable
	:header="$t('tableColumns.field1')"
>
	<template #body="{ data }">
		<span class="d-block text-sm text-white">{{ field1 }}</span>
	</template>
</Column>
```
