### ISSUE TITLE
Dialog: Error when clicking on header to drag

### ISSUE THREAD

**Issue by silvasamu** [primefaces/primevue#5240]
### Describe the bug

When clicking on the Dialog header, to drag, it gives an error.

`TypeError: Failed to execute 'setAttribute' on 'Element': 2 arguments required, but only 1 present.
    at Proxy.initDrag (Dialog.27cf4128.js:7:365)
    at e.visible.e.$slots.container.e.showHeader.o.onMousedown.i.<computed>.i.<computed> (Dialog.27cf4128.js:7:3881)
    at At (entry.9a0f4e23.js:1:13068)
    at Be (entry.9a0f4e23.js:1:13146)
    at HTMLDivElement.n (entry.9a0f4e23.js:1:72052)`

### Reproducer

https://stackblitz.com/run?file=src%2FApp.vue

### PrimeVue version

3.48.1

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

Click on Dalog header to drag

**Comment by mertsincan** [comment]
Fixed in https://github.com/primefaces/primevue/pull/5247
