### ISSUE TITLE
The <Editor> component cannot be used in Nuxt and will report the error ''RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by FatNerdPeng** [primefaces/primevue#5402]
### Describe the bug

Hello,I used a simple example from official document:
```
<template>
  <div class="card">
    <Editor v-model="value" editorStyle="height: 320px" />
  </div>
</template>

<script setup>
const value = ref('')
</script>
```
It did not successfully appear `<Editor>` component, but instead reported an error:
```
[nitro] [unhandledRejection] RangeError: Maximum call stack size exceeded
    at Object.get (file:///home/projects/nuxt-starter-vv2bls/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3195:10)
    at Object.set (file:///home/projects/nuxt-starter-vv2bls/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3111:12)
    at Object.defineProperty (file:///home/projects/nuxt-starter-vv2bls/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3154:12)
    at _0x5f4796.defineProperty (<anonymous>)
    at Object.def (file:///home/projects/nuxt-starter-vv2bls/node_modules/@vue/shared/dist/shared.cjs.js:87:10)
    at Object.markRaw (file:///home/projects/nuxt-starter-vv2bls/node_modules/@vue/reactivity/dist/reactivity.cjs.js:982:12)
    at setupStatefulComponent (file:///home/projects/nuxt-starter-vv2bls/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7545:31)
    at setupComponent (file:///home/projects/nuxt-starter-vv2bls/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7515:36)
    at renderComponentVNode (file:///home/projects/nuxt-starter-vv2bls/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:623:15)
    at Module.ssrRenderComponent (file:///home/projects/nuxt-starter-vv2bls/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:84:10)
[nitro] [unhandledRejection] RangeError: Maximum call stack size exceeded
    at _0x5f4796.keys (<anonymous>)
    at exposeSetupStateOnRenderContext (file:///home/projects/nuxt-starter-vv2bls/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3227:10)
    at handleSetupResult (file:///home/projects/nuxt-starter-vv2bls/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7607:7)
    at setupStatefulComponent (file:///home/projects/nuxt-starter-vv2bls/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7583:7)
```
![image](https://github.com/primefaces/primevue/assets/33616855/1b9ddecf-ae1b-4f86-bfa7-5a444f7d0d01)

Here are my various configuration files:
```
package.json:

{
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "HOST=0.0.0.0 nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "nuxt": "^3.10.3"
  },
  "devDependencies": {
    "nuxt-primevue": "^0.3.1",
    "primeflex": "^3.3.1",
    "primeicons": "^6.0.1",
    "primevue": "^3.49.1",
    "quill": "^1.3.7"
  }
}
```
```
nuxt.config.ts:

export default defineNuxtConfig({
  app: {
    layoutTransition: { name: 'layout', mode: 'out-in' },
    pageTransition: { name: 'page', mode: 'out-in' },
  },
  css: [
    'primeicons/primeicons.css',
    '/node_modules/primeflex/primeflex.css',
    'primevue/resources/themes/md-dark-deeppurple/theme.css',
  ],
  devtools: { enabled: true },
  imports: {
    dirs: ['composables/**'],
  },
  modules: ['nuxt-primevue'],
  primevue: {
    options: {
      ripple: true,
      inputStyle: 'filled',
    },
  },
});
```
I don't know where I got wrong, thanks!

### Reproducer

https://stackblitz.com/edit/nuxt-starter-vv2bls

### PrimeVue version

3.49.1

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

### Browser(s)

Microsoft Edge 122.0.2365.80

### Steps to reproduce the behavior

1. Run `npm run dev`
2. Go  to  `http://.../editor`

**Comment by tugcekucukoglu** [comment]
I want to share a working [example](https://stackblitz.com/edit/nuxt-starter-5uz3su?file=app.vue). Cannot replicate the issue.

**Comment by FatNerdPeng** [comment]
> I want to share a working [example](https://stackblitz.com/edit/nuxt-starter-5uz3su?file=app.vue). Cannot replicate the issue.

Thank you. After reading your example, I rebuilt a simple project and was able to use the editor, which proves that the editor component is not a problem.
