### ISSUE TITLE
ProgressSpinner: Vite build error

### ISSUE THREAD

**Issue by emil14** [primefaces/primevue#5494]
### Describe the bug

Vite error `Two output files share the same path but have different contents` when using spinner component

```
➜  client git:(main) ✗ npm start

> client@0.0.0 start
> npm run dev


> client@0.0.0 dev
> vite


  VITE v5.2.6  ready in 334 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  Vue DevTools: Open http://localhost:5173/__devtools__/ as a separate window
  ➜  Vue DevTools: Press Option(⌥)+Shift(⇧)+D in App to toggle the Vue DevTools

  ➜  press h + enter to show help
[@vue/compiler-sfc] `defineProps` is a compiler macro and no longer needs to be imported.

✘ [ERROR] Two output files share the same path but have different contents: node_modules/.vite/deps_temp_5581c4ce/primevue_progressspinner.js

4:35:59 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
error: Two output files share the same path but have different contents: node_modules/.vite/deps_temp_5581c4ce/primevue_progressspinner.js
    at failureErrorWithLog (/Users/emil/projects/forheygov/client/node_modules/esbuild/lib/main.js:1651:15)
    at /Users/emil/projects/forheygov/client/node_modules/esbuild/lib/main.js:1059:25
    at /Users/emil/projects/forheygov/client/node_modules/esbuild/lib/main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

### Reproducer

im too lazy

### PrimeVue version

3.50

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Browser(s)

Chrome

**Comment by emil14** [comment]
Just add import ProgressSpinner from 'primevue/progressspinner' line to repr with basic vuejs setup from official website based on vite

**Comment by tugcekucukoglu** [comment]
How can we replicate the issue?

**Comment by 2234839** [comment]
i ran into a similar problem when I > rm -r.\node_modules\ and then re pnpm i
```
 Two output files share the same path but have different contents: node_modules\.vite\deps_temp_02a81f20\primevue_toast.js
```
