### ISSUE TITLE
Primevue4: Cannot read properties of undefined (reading 'primevue')

### ISSUE THREAD

**Issue by some-user123** [primefaces/primevue#5852]
### Describe the bug

Plain new nuxt project, install primevue 4, won't run.

```
❯ npm run dev

> dev
> nuxt dev

Nuxt 3.11.2 with Nitro 2.9.6                                                           15:04:56

 ERROR  Cannot read properties of undefined (reading 'primevue')                       15:04:58

  at eval (node_modules/primevue/themes/aura/index.js:1:97)
  at evalModule (node_modules/jiti/dist/jiti.js:1:247518)
  at jiti (node_modules/jiti/dist/jiti.js:1:245331)
  at eval (nuxt.config.ts:1:198)
  at evalModule (node_modules/jiti/dist/jiti.js:1:247518)
  at Object.jiti (node_modules/jiti/dist/jiti.js:1:245331)
  at resolveConfig (node_modules/c12/dist/index.mjs:352:26)
  at Module.loadConfig (node_modules/c12/dist/index.mjs:162:40)
  at async loadNuxtConfig (node_modules/@nuxt/kit/dist/index.mjs:2600:18)
  at async Object.run (node_modules/nuxi/dist/chunks/dev.mjs:183:25) 



 ERROR  Cannot read properties of undefined (reading 'primevue')                       15:04:58
```

### Reproducer

https://stackblitz.com/edit/github-yp4wpc?file=package.json,nuxt.config.ts

### PrimeVue version

4.0.0

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by patriciorivera** [comment]
same problem here.

**Comment by mertsincan** [comment]
Hello,

Please use rc.1 and new @primevue packages. Updated sample;
https://stackblitz.com/edit/github-yp4wpc-tnfmgo?file=package.json,nuxt.config.ts

Best Regards,
