### ISSUE TITLE
SliderComponent Name: Issue Title

### ISSUE THREAD

**Issue by WizPS** [primefaces/primevue#5972]
### Describe the bug

When moving slider a bit beyond max I get error below, running     "primeflex": "^3.3.1", "primeicons": "^7.0.0", "primevue": "^3.52.0",
Uncaught runtime errors:
ERROR
value.toFixed is not a function
TypeError: value.toFixed is not a function
    at Proxy.updateModel (webpack-internal:///./node_modules/primevue/slider/slider.esm.js:110:39)
    at Proxy.setValue (webpack-internal:///./node_modules/primevue/slider/slider.esm.js:107:12)
    at Proxy.onDrag (webpack-internal:///./node_modules/primevue/slider/slider.esm.js:145:14)

### Reproducer

.

### PrimeVue version

3.52.0

### Vue version

3.x

### Language

ALL

### Build / Runtime

Vite

### Browser(s)

Crome and Fox

### Steps to reproduce the behavior

moving slider a bit beyond max 

### Expected behavior

No error

**Comment by tugcekucukoglu** [comment]
Cannot replicate it on the live demo. Could you share a reproducer?
