### ISSUE TITLE
Stepper : the components Stepper not working 

### ISSUE THREAD

**Issue by zz9rodes** [primefaces/primevue#6030]
### Describe the bug

view js does not recognize the slot v-slot="{ activateCallback }" 

### Reproducer

https://stackblitz.com/run?file=src%2FApp.vue

### PrimeVue version

4.0.0-rc.2

### Vue version

3.x

### Language

ES6

### Build / Runtime

Vite

### Browser(s)

Chrome

### Steps to reproduce the behavior

RegisterPage.vue:10  Uncaught (in promise) TypeError: Cannot destructure property 'activateCallback' of 'undefined' as it is undefined.
    at RegisterPage.vue:10:38
    at renderFnWithContext (runtime-core.esm-bundler.js:827:13)
    at normalizeChildren (runtime-core.esm-bundler.js:7382:34)
    at createBaseVNode (runtime-core.esm-bundler.js:7188:5)
    at _createVNode (runtime-core.esm-bundler.js:7265:10)
    at createVNodeWithArgsTransform (runtime-core.esm-bundler.js:7143:10)
    at RegisterPage.vue:10:17
    at renderFnWithContext (runtime-core.esm-bundler.js:827:13)
    at normalizeChildren (runtime-core.esm-bundler.js:7382:34)
    at createBaseVNode (runtime-core.esm-bundler.js:7188:5)
(anonymes) @ RegisterPage.vue:10
renderFnWithContext @ runtime-core.esm-bundler.js:827
normalizeChildren @ runtime-core.esm-bundler.js:7382
createBaseVNode @ runtime-core.esm-bundler.js:7188
_createVNode @ runtime-core.esm-bundler.js:7265
createVNodeWithArgsTransform @ runtime-core.esm-bundler.js:7143
(anonymes) @ RegisterPage.vue:10
renderFnWithContext @ runtime-core.esm-bundler.js:827
normalizeChildren @ runtime-core.esm-bundler.js:7382
createBaseVNode @ runtime-core.esm-bundler.js:7188
_createVNode @ runtime-core.esm-bundler.js:7265
createVNodeWithArgsTransform @ runtime-core.esm-bundler.js:7143
(anonymes) @ RegisterPage.vue:9
renderFnWithContext @ runtime-core.esm-bundler.js:827
renderSlot @ runtime-core.esm-bundler.js:2108
render @ Stepper.vue:4
renderComponentRoot @ runtime-core.esm-bundler.js:887
componentUpdateFn @ runtime-core.esm-bundler.js:5133
run @ reactivity.esm-bundler.js:183
instance.update @ runtime-core.esm-bundler.js:5264
setupRenderEffect @ runtime-core.esm-bundler.js:5274
mountComponent @ runtime-core.esm-bundler.js:5042
processComponent @ runtime-core.esm-bundler.js:4996
patch @ runtime-core.esm-bundler.js:4468
mountChildren @ runtime-core.esm-bundler.js:4710
mountElement @ runtime-core.esm-bundler.js:4623
processElement @ runtime-core.esm-bundler.js:4588
patch @ runtime-core.esm-bundler.js:4456
componentUpdateFn @ runtime-core.esm-bundler.js:5140
run @ reactivity.esm-bundler.js:183
instance.update @ runtime-core.esm-bundler.js:5264
setupRenderEffect @ runtime-core.esm-bundler.js:5274
mountComponent @ runtime-core.esm-bundler.js:5042
processComponent @ runtime-core.esm-bundler.js:4996
patch @ runtime-core.esm-bundler.js:4468
componentUpdateFn @ runtime-core.esm-bundler.js:5220
run @ reactivity.esm-bundler.js:183
instance.update @ runtime-core.esm-bundler.js:5264
callWithErrorHandling @ runtime-core.esm-bundler.js:195
flushJobs @ runtime-core.esm-bundler.js:409
Promise.then (asynchrone)
queueFlush @ runtime-core.esm-bundler.js:319
queuePostFlushCb @ runtime-core.esm-bundler.js:339
queueEffectWithSuspense @ runtime-core.esm-bundler.js:1760
scheduler @ runtime-core.esm-bundler.js:6113
resetScheduling @ reactivity.esm-bundler.js:268
triggerEffects @ reactivity.esm-bundler.js:321
triggerRefValue @ reactivity.esm-bundler.js:1089
set value @ reactivity.esm-bundler.js:1136
finalizeNavigation @ vue-router.mjs:3460
(anonymes) @ vue-router.mjs:3325
Promise.then (asynchrone)
pushWithRedirect @ vue-router.mjs:3292
push @ vue-router.mjs:3217
install @ vue-router.mjs:3659
use @ runtime-core.esm-bundler.js:2984
(anonymes) @ main.js:12
Afficher 51 plus de cadres
Afficher moins
register:1  Unchecked runtime.lastError: The message port closed before a response was received.

### Expected behavior

`<template>
    <div class="card flex justify-center">
        <Stepper value="1" class="basis-[50rem]">
            <StepList>
                <Step value="1">Header I</Step>
                <Step value="2">Header II</Step>
                <Step value="3">Header III</Step>
            </StepList>
            <StepPanels>
                <StepPanel v-slot="{ activateCallback }" value="1">
                    <div class="flex flex-col h-48">
                        <div class="border-2 border-dashed border-surface-200 dark:border-surface-700 rounded bg-surface-50 dark:bg-surface-950 flex-auto flex justify-center items-center font-medium">Content I</div>
                    </div>
                    <div class="flex pt-6 justify-end">
                        <Button label="Next" icon="pi pi-arrow-right" iconPos="right" @click="activateCallback('2')" />
                    </div>
                </StepPanel>
                <StepPanel v-slot="{ activateCallback }" value="2">
                    <div class="flex flex-col h-48">
                        <div class="border-2 border-dashed border-surface-200 dark:border-surface-700 rounded bg-surface-50 dark:bg-surface-950 flex-auto flex justify-center items-center font-medium">Content II</div>
                    </div>
                    <div class="flex pt-6 justify-between">
                        <Button label="Back" severity="secondary" icon="pi pi-arrow-left" @click="activateCallback('1')" />
                        <Button label="Next" icon="pi pi-arrow-right" iconPos="right" @click="activateCallback('3')" />
                    </div>
                </StepPanel>
                <StepPanel v-slot="{ activateCallback }" value="3">
                    <div class="flex flex-col h-48">
                        <div class="border-2 border-dashed border-surface-200 dark:border-surface-700 rounded bg-surface-50 dark:bg-surface-950 flex-auto flex justify-center items-center font-medium">Content III</div>
                    </div>
                    <div class="pt-6">
                        <Button label="Back" severity="secondary" icon="pi pi-arrow-left" @click="activateCallback('2')" />
                    </div>
                </StepPanel>
            </StepPanels>
        </Stepper>
    </div>
</template>

<script>
export default {
  methods: {
    activateCallback(value) {
      // Implémentez ici la logique pour activer l'étape correspondante
      console.log('Activating step:', value);
    }
  }
}
</script>`

**Comment by tugcekucukoglu** [comment]
Please try to use the latest version.
