### ISSUE TITLE
PrimeVue API: migration from v3 to v4 error

### ISSUE THREAD

**Issue by nathanaelytj** [primefaces/primevue#6327]
### Describe the bug

After migrating to PrimeVue v4, Rollup failed to resolve import "@primevue/core/api"

This can be fixed with adding @primevue/core to dependencies.

Bellow is rollup error log:
`vite v5.4.2 building for production...
✓ 219 modules transformed.
x Build failed in 6.34s
error during build:
[vite]: Rollup failed to resolve import "@primevue/core/api" from "/app/resources/vue/SuperPages/PgRoleMan.vue?vue&type=script&setup=true&lang.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///app/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.2_sass@1.77.8_terser@5.31.6/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:65477:17)
    at onRollupWarning (file:///app/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.2_sass@1.77.8_terser@5.31.6/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:65509:5)
    at onwarn (file:///app/node_modules/.pnpm/vite@5.4.2_@types+node@22.5.2_sass@1.77.8_terser@5.31.6/node_modules/vite/dist/node/chunks/dep-BzOvws4Y.js:65172:7)
    at file:///app/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:18668:13
    at Object.logger [as onLog] (file:///app/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:20306:9)
    at ModuleLoader.handleInvalidResolvedId (file:///app/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:19257:26)
    at file:///app/node_modules/.pnpm/rollup@4.21.2/node_modules/rollup/dist/es/shared/node-entry.js:19215:26
 ELIFECYCLE  Command failed with exit code 1.`

### Reproducer

None

### PrimeVue version

4.0.5

### Vue version

3.x

### Language

TypeScript

### Build / Runtime

Vite

### Steps to reproduce the behavior

1. Create project with primevue v3
2. Use `primevue/api`
3. Upgrade the project to v4
4. Change `primevue/api` to `@primevue/core/api`
5. Run Vite build. Vite will return error due to unresolved import

### Expected behavior

Vite build successsfully

**Comment by zbuhler** [comment]
I had the same issue, though I'm not using rollup. I saw the PR for updating the docs to add it as a top-level dependency which thankfully worked, however, I'm wondering if it should necessarily have to be a top-level dependency when @primevue itself already has /core/api? Maybe the intent is to break it off into its own thing?

**Comment by nathanaelytj** [comment]
Seems related to #6117 ?

**Comment by tsipiniuk** [comment]
Seems to be the same problem. I install via pnpm and there is a problem, I install via yarn and the necessary packages are loaded and everything works.

**Comment by tugcekucukoglu** [comment]
Could you send a reproducer? Migration guide could help: https://primevue.org/guides/migration/v4/

**Comment by nathanaelytj** [comment]
Mark as solved since adding deps package to package.json solved the issue.
