### ISSUE TITLE
Drawer: Wacky issues depending on context

### ISSUE THREAD

**Issue by LeaderbotX400** [primefaces/primevue#6734]
### Describe the bug

if I run the code[1] in a component (e.g. `CustomDrawer`) It errors out[2]. However, when I run it as a nuxt page, or at the root `app.vue` it works just fine. Running the same code, but removing the `Drawer` works just fine as a component. 

Mostly posting this here to see if anyone else has this issue as I am in the process of creating a minimal repro

# 1
```vue
<script setup lang="ts">
  const active = ref(0);

  const visible = ref(false);

  const target = ref<HTMLDivElement | null>(null);

  const { lengthY } = useSwipe(target, {
    passive: true,
    onSwipeEnd: (evt, dir) => {
      visible.value = dir === "up" && lengthY.value > 100;
    },
  });
</script>

<template>
  <div>
    <div class="absolute bottom-0 left-0 my-5 w-svw outline">
      <div>
        <div
          class="flex items-center justify-center overflow-hidden select-none"
        >
          <button ref="target" @click="visible = true">
            <Icon name="mdi:chevron-up" size="2rem" />
          </button>
        </div>
        <div id="scene-controls" class="grid grid-cols-2 gap-2">
          <button
            v-for="i in 4"
            :key="i"
            :class="[
              'p-2 m-2 bg-blue-500 text-white rounded-lg',
              {
                'bg-red-500': active === i,
              },
            ]"
            @click="console.log(i)"
          >
            {{ `Scene ${i}` }}
          </button>
        </div>
      </div>
      <Drawer
        v-model:visible="visible"
        position="bottom"
        style="height: auto"
        closeIcon="pi pi-chevron-down"
        :showCloseIcon="false"
        modal
      >
        <template #header>
          <div
            class="flex items-center justify-center overflow-hidden select-none w-full"
          >
            <button ref="target" @click="visible = false">
              <Icon name="mdi:chevron-down" size="2rem" />
            </button>
          </div>
        </template>
        <div id="scene-controls" class="grid grid-cols-2 gap-2">
          <button
            v-for="i in 4"
            :key="i"
            :class="[
              'p-2 m-2 bg-blue-500 text-white rounded-lg',
              {
                'bg-red-500': active === i,
              },
            ]"
            @click="console.log(i)"
          >
            {{ `Scene ${i}` }}
          </button>
        </div>

        <div id="extra-controls" class="outline">
          <div class="grid grid-cols-2">
            <div class="p-2 m-2 bg-blue-500 text-white rounded-lg">1</div>
            <div class="p-2 m-2 bg-blue-500 text-white rounded-lg">2</div>
            <div class="p-2 m-2 bg-blue-500 text-white rounded-lg">3</div>
            <div class="p-2 m-2 bg-blue-500 text-white rounded-lg">4</div>
          </div>
        </div>
      </Drawer>
    </div>
  </div>
</template>
```
# 2
![image](https://github.com/user-attachments/assets/2cff0e5a-e7de-4222-9661-9962eda1643e)

```
Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at processCommentNode (runtime-core.esm-bundler.js:4722:30)
    at patch (runtime-core.esm-bundler.js:4627:9)
    at mountChildren (runtime-core.esm-bundler.js:4895:7)
    at mountElement (runtime-core.esm-bundler.js:4818:7)
    at processElement (runtime-core.esm-bundler.js:4783:7)
    at patch (runtime-core.esm-bundler.js:4651:11)
    at mountChildren (runtime-core.esm-bundler.js:4895:7)
    at mountElement (runtime-core.esm-bundler.js:4818:7)
    at processElement (runtime-core.esm-bundler.js:4783:7)
    at patch (runtime-core.esm-bundler.js:4651:11)
```

### Reproducer

Not currently available (Working on it)

### PrimeVue version

4.2.1

### Vue version

4.x

### Language

TypeScript

### Build / Runtime

Nuxt

**Comment by tugcekucukoglu** [comment]
Can you provide a reproducer demo link?
