### ISSUE TITLE
Quickstart app is not working in CodeSandbox

### ISSUE THREAD

**Issue by wobsoriano** [primefaces/primevue#738]
Imported the [quickstart repo](https://github.com/primefaces/primevue-quickstart) in CodeSandbox and can't get it to work.

Link: https://codesandbox.io/s/competent-sun-zls6m

Trace:

```
SyntaxError: Unexpected token '<'
    at eval (<anonymous>)

    at z (https://codesandbox.io/static/js/sandbox.36bcd2ca2.js:1:98389)

    at X.evaluate (https://codesandbox.io/static/js/sandbox.36bcd2ca2.js:1:110554)

    at ye.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.36bcd2ca2.js:1:120134)

    at c (https://codesandbox.io/static/js/sandbox.36bcd2ca2.js:1:110300)

    at evaluate (https://zls6m.csb.app/node_modules/primevue/components/inputtext/InputText.vue:5:26)

    at z (https://codesandbox.io/static/js/sandbox.36bcd2ca2.js:1:98430)

    at X.evaluate (https://codesandbox.io/static/js/sandbox.36bcd2ca2.js:1:110554)

    at ye.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.36bcd2ca2.js:1:120134)

    at c (https://codesandbox.io/static/js/sandbox.36bcd2ca2.js:1:110300)

    at evaluate (https://zls6m.csb.app/node_modules/primevue/inputtext.js:2:18)

    at z (https://codesandbox.io/static/js/sandbox.36bcd2ca2.js:1:98430)

    at X.evaluate (https://codesandbox.io/static/js/sandbox.36bcd2ca2.js:1:110554)

    at ye.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.36bcd2ca2.js:1:120134)

    at c (https://codesandbox.io/static/js/sandbox.36bcd2ca2.js:1:110300)

    at evaluate (https://zls6m.csb.app/src/main.js:9:41)

    at z (https://codesandbox.io/static/js/sandbox.36bcd2ca2.js:1:98430)

    at X.evaluate (https://codesandbox.io/static/js/sandbox.36bcd2ca2.js:1:110554)

    at ye.evaluateTranspiledModule (https://codesandbox.io/static/js/sandbox.36bcd2ca2.js:1:120134)

    at ye.evaluateModule (https://codesandbox.io/static/js/sandbox.36bcd2ca2.js:1:119870)

    at https://codesandbox.io/static/js/sandbox.36bcd2ca2.js:1:809679

    at l (https://codesandbox.io/static/js/common-sandbox.567fd683a.chunk.js:1:256720)

    at Generator._invoke (https://codesandbox.io/static/js/common-sandbox.567fd683a.chunk.js:1:256473)

    at Generator.forEach.e.<computed> [as next] (https://codesandbox.io/static/js/common-sandbox.567fd683a.chunk.js:1:257077)

    at t (https://codesandbox.io/static/js/common-sandbox.567fd683a.chunk.js:1:2405)

    at i (https://codesandbox.io/static/js/common-sandbox.567fd683a.chunk.js:1:2616)
```

![Screen Shot 2020-12-05 at 2 23 06 PM](https://user-images.githubusercontent.com/13049130/101235666-334d4c00-3705-11eb-913b-ae30aa40d59c.png)

Even tried with a fresh Vue 3 project with a single primevue component imported. Same error.

**Comment by tugcekucukoglu** [comment]
It was fixed [https://yzcyv.csb.app/](https://yzcyv.csb.app/)
