### ISSUE TITLE
Failed to build 2.3.0-SNAPSHOT

### ISSUE THREAD

**Issue by tarkhil** [primefaces/primevue#879]
On branch 2.x

npm run build-lib

```
Building uniquecomponentid
-  Building for production as library (commonjs,umd,umd-min)...
fs.js:52
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:52:5
    at req_ (/usr/home/tarkhil/work/primevue/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/usr/home/tarkhil/work/primevue/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/usr/home/tarkhil/work/primevue/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
```

**Comment by cagataycivici** [comment]
This is due to a mismatch between gulp and node.js, not PrimeVue related.

**Comment by tarkhil** [comment]
Can't you please be more specific?
